name = "Krysha"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
summaryLength = 15
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Mark"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[build]
  writeStats = true
